# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: surge-downloader.surge
PackageVersion: 0.11.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: surge.exe
  PortableCommandAlias: surge
InstallModes:
- silent
UpgradeBehavior: uninstallPrevious
Commands:
- surge
ReleaseDate: 2026-08-03
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/SurgeDM/Surge/releases/download/v0.11.2/Surge_0.11.2_windows_386.zip
  InstallerSha256: 179560c37a32fb1a48b36021eced0697fc96d7f7f2c6a6f948385b354f4de9d1
- Architecture: x64
  InstallerUrl: https://github.com/SurgeDM/Surge/releases/download/v0.11.2/Surge_0.11.2_windows_amd64.zip
  InstallerSha256: cdc5f26ffcebb027437f256e9a8c1d0d6bf26f1fe9bc2cb8f21c487795934ee1
- Architecture: arm64
  InstallerUrl: https://github.com/SurgeDM/Surge/releases/download/v0.11.2/Surge_0.11.2_windows_arm64.zip
  InstallerSha256: 95fc88a95fa78d80da075725e84aeb3195cd09e56776b91e6f3849d110e421f3
ManifestType: installer
ManifestVersion: 1.12.0
